### ISSUE TITLE
alarm list - on/off bug

### ISSUE THREAD

**Issue by algazarra** [drpout/boilr#133]
after reordering my alarm list I tried turning on/off the 3rd alarm. this turned off the first alarm. toggling on/off the 3rd alarm, only changed the 1st alarm. nothing else.

the turn on/off worked on every other alarm

**Comment by dllud** [comment]
Steps to reproduce something similar:
1. Create 3 alarms.
2. Delete 2nd alarm (middle one). While the undo toast is shown get out of the app and remove it from the OS open app's list (i.e. destroy the activity).
3. Create a new alarm.
4. Turn the 2nd alarm on/off, it will affect the 3rd alarm instead.
