### ISSUE TITLE
Permissions - read phone status and identity

### ISSUE THREAD

**Issue by algazarra** [drpout/boilr#135]
Is there another way of stopping an alarm if during a phone call?

**Comment by dllud** [comment]
No.

**Comment by dllud** [comment]
After all the READ_PHONE_STATE permission is unnecessary with the [TelephonyManager.getCallState()](http://developer.android.com/reference/android/telephony/TelephonyManager.html) call we're using. Probably an artefact left on the Manifest from a previous implementation with a Broadcast Receiver. My bad.
