### ISSUE TITLE
Option for separate price hit up/down alarms

### ISSUE THREAD

**Issue by xeverse** [drpout/boilr#138]
First, thanks for price change alarms! 
Testing these.

It may be be just me but 
maybe it would be a good idea to have an option
for separate up and down alarms instead of range type.

Up and down price targets are pretty independent to my mind.

Which is even more important 
that way different alarm sounds could be assigned too.

**Comment by dllud** [comment]
@xeverse Thanks for the input!

Right now you can leave the setting for a given limit empty. That way it will be replaced by the corresponding infinity and act as if it wasn't there.

![setting-empty-limit-small](https://cloud.githubusercontent.com/assets/1716156/6919302/d3f9c5d8-d7ad-11e4-8e06-8b020bab78d1.png)   ![alarms-infinit-limit-small](https://cloud.githubusercontent.com/assets/1716156/6919308/d6f0f518-d7ad-11e4-8f7a-ebae1b8fc40f.png)

Does this serve your purpose? If so, perhaps we should add it to a FAQ.

**Comment by algazarra** [comment]
or add a small note in the description

**Comment by xeverse** [comment]
Wow surpising, apparently that did it. Thanks!
