### ISSUE TITLE
Snooze on retrace

### ISSUE THREAD

**Issue by xeverse** [drpout/boilr#139]
Another thing, an option for
alarm auto silencing itself if price manages
to retrace back above/belove the price hit value
after it has been triggered. 
Testing that as well atm..
##

**Comment by algazarra** [comment]
Kudos

**Comment by dllud** [comment]
This would bring a major issue. Usually markets have a tendency to test a given high/low and retrace immediately on the next trade. Thus, it is really common that the first price you get after a trigger is below/over the trigger price. That would silence most alarms rather quickly (after one update interval, e.g. 30s), giving it no time to wake you up.

**Comment by algazarra** [comment]
If it's optional it's perfect. I also felt the need for this. It's a good suggestion. Ty @xeverse

**Comment by dllud** [comment]
I feel this option may be rather useless. You would only be able to use it on alarms with a long update interval. I bet the first value after a trigger limit is most of the times below/over the limit.

@algazarra Please gather some market data and paste here to (in)validate this enhancement.

**Comment by xeverse** [comment]
@dllud one should better set his alams a little bit infront/behind
his significant market levels therefore giving it some room for waking up..

**Comment by dllud** [comment]
@xeverse That won't solve the problem. This issue is the alarm will ring for a short period of time, as the next value will most probably shut it off.

Give a look at the trade history here: https://bitcoinwisdom.com/markets/huobi/btccny
Green, red, green, red, ...

**Comment by xeverse** [comment]
@dllud that kind of functionality is precisely what i'm looking for.
if it breaks second time it should ring again and he third and so on ad inf

**Comment by dllud** [comment]
Ohh, I see. Ok then. Thus the alarm should be silenced but kept on.

**Comment by xeverse** [comment]
Riiight.

**Comment by xeverse** [comment]
@algazarra what a mysterious avatar/logo. what is it all about? represents symbolically?

**Comment by algazarra** [comment]
@xeverse TY
please check - https://cargocollective.com/algazarra/Boilr-android-app
