### ISSUE TITLE
Add SAE to NXT Asset Exchange name

### ISSUE THREAD

**Issue by algazarra** [drpout/boilr#142]
trade.secureae.com

**Comment by dllud** [comment]
trade.secureae.com == NXT Asset Exchange

**Comment by algazarra** [comment]
What if i search SAE in the exchange list?

**Comment by dllud** [comment]
Anyone who uses SAE knows it is an interface for NXT Asset Exchange.

**Comment by algazarra** [comment]
Sure, but what name will he search?

**Comment by dllud** [comment]
Wanna change the name of "NXT Asset Exchange" to "NXT Asset Exchange (SAE)"? But them we miss the Secureae name.

**Comment by algazarra** [comment]
Maybe each name in the list could have searchable metadata. This would open space for categories and tags both for exchanges as coins or alarms right?

**Comment by dllud** [comment]
Yup, doable although not that much useful. People won't search for anything they are not reading on the screen. Anyway please open a separate issue for the metadata.

(Alarms already have some *metadata*, try searching "hit" or "change" on the alarm list.)

Concerning this issue, I'll change the name to "NXT Asset Exchange (SAE)".

**Comment by algazarra** [comment]
If you can find it on the screen you wouldn't search it eheh

**Comment by dllud** [comment]
This is now invalid. SAE no longer acts as proxy for NXT Asset Exchange.
