### ISSUE TITLE
no internet forever

### ISSUE THREAD

**Issue by algazarra** [drpout/boilr#150]
The no internet notif is popping up every 5-10mins since yesterday. Tried force shutting down. But problem persists. I can browse on ff

**Comment by dllud** [comment]
Probably solved with 07600f880d090f39bf40bd10f61e00a10a06018e
Reopen if it happens again with version 0.7.0

**Comment by algazarra** [comment]
it's happening again. tested on two different networks

**Comment by algazarra** [comment]
this issue is terribly annoying. I had to force down boilr till this gets fixed... It's maddening

**Comment by dllud** [comment]
Sure it's happening. You are using version 0.6.0. That was fixed on 0.7.0. I'll send you a fresh build soon.

**Comment by algazarra** [comment]
New build fixed it
