### ISSUE TITLE
Add BL3p exchange

### ISSUE THREAD

**Issue by dllud** [drpout/boilr#162]
https://bl3p.com/api

Not online yet.

**Comment by algazarra** [comment]
low volume and high fees, but great to see europe coming waking up! btw please PM me the source where you found it!

**Comment by algazarra** [comment]
it's online

**Comment by dllud** [comment]
https://api.bl3p.eu/1/BTCEUR/ticker

https://github.com/BitonicNL/bl3p-api/blob/master/docs/public_api/rest.md
