### ISSUE TITLE
Add FoxBit (Brazilian Exchange)

### ISSUE THREAD

**Issue by schiavonxv** [drpout/boilr#169]
Please, add FoxBit (www.foxbit.com.br)

Our API:

Trades: https://api.blinktrade.com/api/v1/BRL/trades?crypto_currency=BTC
Ticker: https://api.blinktrade.com/api/v1/BRL/ticker?crypto_currency=BTC
Orderbook: https://api.blinktrade.com/api/v1/BRL/orderbook?crypto_currency=BTC

Thank you ;)

**Comment by dllud** [comment]
Thanks @schiavonxv I'll add it soon.
Meanwhile, if you have some time, please consider adding it yourself. It won't take you long and you can find some good instructions at [libdynticker's CONTRIBUTING.md](https://github.com/drpout/libdynticker/blob/master/CONTRIBUTING.md)
