### ISSUE TITLE
adding swisscex.com ?

### ISSUE THREAD

**Issue by algazarra** [drpout/boilr#192]
can't open the website. what about you?

**Comment by dllud** [comment]
I'm also unable to open the website. The same was happening in January when I first tried to add this exchange.

**Comment by algazarra** [comment]
it's not white, it flashes for 1sec some of the page's navigation links but then goes blank. I have a screenshot on my desktop.

**Comment by andrefbsantos** [comment]
The page is there but all the script used inside the page are not available, that's why we can properly rend the page.

**Comment by algazarra** [comment]
they must be real pros!

**Comment by andrefbsantos** [comment]
Swisscex.com is dead.
They file for solvency and close their doors.
https://twitter.com/swisscex/status/575090576594464768

**Comment by algazarra** [comment]
Looks nasty. If they're solvent why would they freeze wallet access, or consider closing? This is dead for me too. Leave it closed eheh
