### ISSUE TITLE
add btcxindia.com

### ISSUE THREAD

**Issue by algazarra** [drpout/boilr#199]
https://btcxindia.com/api/

**Comment by algazarra** [comment]
"India’s Bitcoin Exchange BTCXIndia to Close Following Loss of Banking Support" - http://cointelegraph.com/news/114224/indias-bitcoin-exchange-btcxindia-to-close-following-loss-of-banking-support

**Comment by dllud** [comment]
After all it is still live and increasing in volume: http://blog.btcxindia.com
