### ISSUE TITLE
add btcchina.com

### ISSUE THREAD

**Issue by algazarra** [drpout/boilr#211]
Biggest exchange

**Comment by andrefbsantos** [comment]
Already implemented.

https://github.com/drpout/libdynticker/blob/master/src/main/java/mobi/boilr/libdynticker/exchanges/BTCChinaExchange.java

**Comment by algazarra** [comment]
My bad, please change name in list to btcchina couldn't find in search

**Comment by andrefbsantos** [comment]
Done.
drpout/libdynticker@6dd33c02229781eab98ae725e06ef6c846a5b226
