### ISSUE TITLE
add Coinsquare.io

### ISSUE THREAD

**Issue by algazarra** [drpout/boilr#214]

**Comment by dllud** [comment]
No API?

**Comment by algazarra** [comment]
submitted ticket, will update ASAP

**Comment by algazarra** [comment]
They replied with:
"Our full API documentation in still under development. You can however use the following GET methods to obtain the latest quotes and order books. The prices and quantities are in Satoshis.

GET: method="quotes" example
GET: method="book",ticker=[ticker code],base=[base ticker code] example" - https://coinsquare.io/?method=img&tag=RESZFAQ

**Comment by dllud** [comment]
https://coinsquare.io/?method=quotes
