### ISSUE TITLE
Clicking a Boilr's notification when an alarm is rigging does not turn off the alarm

### ISSUE THREAD

**Issue by algazarra** [drpout/boilr#237]
if you open an alarm through the notification, and then you leave the alarm window without shutting the alarm, it keeps ringing until the app is shut down. There's no way of returning to the alarm window without the notification.

Shouldn't the status bar notification be persistent while the alarm is ringing?

**Comment by dllud** [comment]
Actually, the alarm should be silenced once you click the notification. That's the current behaviour for any action that hides the alarm activity, such as clicking the home button or clicking the notification of any other app.

Thus there is a bug around here. When you click a notification for Boilr itself this jumps over the code that should defuse the alarm.
