### ISSUE TITLE
Seller takes transaction fee and sequrity diposit?

### ISSUE THREAD

**Issue by martinschultzkristensen** [drpout/boilr#250]
Hallo there Bitsquare.
When you buy on Bitsquare there is this an offer fee and a multiSig deposit. I understand that you get this deposit back after succeed buy. If that is the case I find that I haven't received mine. I have attached the transaction.csv. I hope you can see enough from there to confirm or de-confirm my thoughts.
Best regards Martin

[transactions.csv.zip](https://github.com/drpout/boilr/files/917271/transactions.csv.zip)

**Comment by dllud** [comment]
You've posted to the wrong place. We are not Bitsquare and we have nothing to do with them,

**Comment by martinschultzkristensen** [comment]
Ok.
Sorry. New on Github.
