### ISSUE TITLE
Blinktrade based exchanges not working

### ISSUE THREAD

**Issue by nackox** [drpout/boilr#253]
Hi. I’ve been using boilr for quite some time now and was working great till a couple of days ago. I thought it was an issue with my wifi and verified that the request was going through when upgrade was scheduled. After that, I verified that there wasn’t any app that was dozing boilr and final step was to contact the devs (Thanks dllud). 

 Looks like there is an issue with all exchanges that I'm monitoring which depend on "Blinktrade".  The are chilebit, surbitcoin and surbtc

**Comment by dllud** [comment]
ChileBit, SurBitcoin and all other BlinkTrade based exchanges are now working. The error was fixed on BlinkTrade's side.
