### ISSUE TITLE
Gulden?

### ISSUE THREAD

**Issue by trymz** [drpout/boilr#256]
Hello,
I love your app but please can you add Gulden from www.guldenrate.com ?
Thank for all your work.

**Comment by dllud** [comment]
Hi,

There is no need to add [guldenrate.com](https://www.guldenrate.com) since Boilr already supports Bittrex, which is [the major exchange for Gulden](https://coinmarketcap.com/currencies/gulden/#markets) and the one used by [guldenrate.com](https://www.guldenrate.com) for price calculations.

**Comment by trymz** [comment]
Hi, 
Thank for your time.
Yes Bittrex work well but have no NLG/EUR pairs,only NLG/BTC.

**Comment by dllud** [comment]
On the [Gulden Markets on CoinMarketCap](https://coinmarketcap.com/currencies/gulden/#markets) you can see that all markets with the NLG/EUR pair are not real exchanges (multilateral trading facilities) but rather bureaus de change.
In Boilr we only support exchanges. The price on bureaus de change follows that of exchanges. In your case, the NLG/EUR price is just the compounded price of NLG/BTC plus BTC/EUR.
