### ISSUE TITLE
Add Coinbase

### ISSUE THREAD

**Issue by ahokinson** [drpout/boilr#267]
REST API: https://developers.coinbase.com/api/v2

**Comment by dllud** [comment]
We removed Coinbase and replaced it by GDAX on December 2016 after GDAX was launched.
Though it now seems they are keeping both exchanges operational. Coinbase as a consumer-grade platform and GDAX as the professional one.

The question is: do both operate on the same orderbook, or are all markets totally independent?

**Comment by refola** [comment]
> do both operate on the same orderbook, or are all markets totally independent

AFAIK, Coinbase uses the same price data¹, and presumably the same underlying infrastructure, but they completely hide the orderbook. Buying and selling happens 'instantly'², but Coinbase takes a ~1-2% cut. Presumably part of Coinbase's cut goes towards making it match existing buy/sell orders, which shouldn't be too hard given the relatively low buy/sell limits on Coinbase's consumer accounts.

That said, even if Coinbase is strictly redundant, it would still be useful for future people at what my level of knowledge was when I first ran Boilr.

¹ This confused me when I first set up Boilr and couldn't find Coinbase. Then some research brought me to GDAX where I saw wayyyy more info than Coinbase ever showed.
² The price at that instant is used to determine the conversion rate, but it can take almost a week to actually get your converted (crypto or fiat) money.

**Comment by refola** [comment]
GDAX is now becoming Coinbase Pro, so it looks like "Add Coinbase" matters now.

The announcement at https://blog.coinbase.com/transition-to-coinbase-pro-db8f9b574ad2 says:
> GDAX API Integrations:
> -    There will be no disruption to the gdax.com API during this time. GDAX APIs will continue to function until December 31, 2018.
> -    We encourage Coinbase Pro users to begin migrating their API usage away from api.gdax.com to api.pro.coinbase.com.

**Comment by dllud** [comment]
@refola Thanks for letting us know. I have opened a new issue for this: [Replace GDAX with Coinbase Pro #287](https://github.com/drpout/boilr/issues/287).
