### ISSUE TITLE
Kraken DASH Support

### ISSUE THREAD

**Issue by gordonsross** [drpout/boilr#273]
Hi, great app, I really like it. 

One issue I see is that when trying to add DASH/EUR on Kraken I'm told that the app cannot retrieve a price for the pair. I see in the pairs list for Kraken on Boilr the pair names are of the format ###/### whereas on Kraken DASH is four characters long. Is that part of the issue?

Thanks

Gordon

**Comment by dllud** [comment]
Fixed on master. Will be available with next release. Meanwhile you can test it with the following apk that I've just built and signed: [boilr-0.8.0-rc2.apk.zip](https://github.com/drpout/boilr/files/1321960/boilr-0.8.0-rc2.apk.zip)

Kraken is finally realising that using X (cryptocurrency) and Z (FIAT) prefixes on coin tickers just added to the confusion. They are now moving away from this on all new pairs, which breaked our previous code.

**Comment by gordonsross** [comment]
Stylish, that's worked on the "boilr-0.8.0-rc2.apk.zip" package.

Thank you. Donation on it's way to your bitcoin address.
