### ISSUE TITLE
Kraken pairs not working, bug with currency code?

### ISSUE THREAD

**Issue by fm444fm** [drpout/boilr#276]
There are several pairs (CH/*, ASH/*, OS/*, NO/*, SDT/*) of currencies not working on kraken.
Should maybe CH be actually BCH? ASH > DASH, OS > EOS, NO > GNO, SDT > USDT?
It seems for these pairs the first letter is missing and hence "cannot retrieve last value..." message appears

**Comment by dllud** [comment]
Duplicate of #273
