### ISSUE TITLE
add bitmex.com/

### ISSUE THREAD

**Issue by algazarra** [drpout/boilr#84]
BitMEX is a btc derivatives trading platform

**Comment by andrefbsantos** [comment]
BitMEX doesn't have a ticker and requires a key to get the trade history.

**Comment by algazarra** [comment]
This is Samuel Reed's reply:

We do have a realtime ticker via Websocket. To access it, connect to:
"wss://www.bitmex.com/realtime/websocket?subscribe=instrument"

You will see update messages as they happen. We publish deltas to all of our underlying instruments here. This includes volume, vwap, turnover, open interest and price data.

For example:
< {"table":"instrument","action":"update","data":[{"symbol":"XBUH15","totalVolume":145379,"volume":576,"totalTurnover":5978599686862,"turnover":19637630596,"vwap":293.3144,"lastPrice":293.21,"lastTickDirection":"PlusTick","lastChangePcnt":-0.011296196385217283,"timestamp":1417866813692}]}

Only changed fields will be published. You can get full starting Instrument data one of two ways:
Hit `https://www.bitmex.com/api/v1/instrument` to receive full data through HTTP, or

Push the message '{"op": "getSymbol", "args": [<symbols>]}' - ask for the symbols you want to receive and they will be pushed back to you through the websocket.

**Comment by dllud** [comment]
We need a REST API. We cannot use a WebSocket API.

**Comment by algazarra** [comment]
https://www.bitmex.com/app/restAPI
https://www.bitmex.com/api/explorer/

**Comment by dllud** [comment]
https://www.bitmex.com/api/v1/stats
